### ISSUE TITLE
StripOffsets causing overflows when the tag type is SHORT

### ISSUE THREAD

**Issue by Fraaankes** [BitMiracle/libtiff.net#18] opened 2015-12-19 13:16 UTC
I have recently been using your excelent library to merge some tiff files, but I've come across an issue.
The tiffs im getting from a 3rd party, is using the tag type SHORT for StripOffset (273) whenever the tiffs are below 64k in size.
This is producing overfow errors for all the offsets above 32k as you use short instead of ushort as the datatype.
Is there any reason for using the signed type ? Im assuming the offsets cant be negative.

**Comment by Bobrovsky** [comment] 2015-12-22 16:28
Hello Fraaankes,

The signed type is used because not all .NET languages have unsigned types. 
Please feel free to provide some code to reproduce the issue. Or place a pull a request with a fix.

**Comment by Fraaankes** [comment] 2016-01-05 16:44
Hello Bobrovsky
Sorry for the delay, holidays came and went :)
I believe I have a fix for it (works on my machine at least). Do I need special access to create a branch for it to be able to create a pull request ?

**Comment by Bobrovsky** [comment] 2016-01-05 16:53
Hello Fraaankes,

Please test you fix with existing unit test (and feel free to add a new one). Then please post a pull request. 

You do not need any permissions from us to be able to fork the repository and post pull a request.

**Comment by Bobrovsky** [comment] 2016-01-08 11:16
The issue is fixed by https://github.com/BitMiracle/libtiff.net/pull/19

**Closed by Bobrovsky** 2016-01-08 11:16 UTC
